config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meetup.rb
module Meetup
  @@events_root      = "https://api.meetup.com/2/open_events"
  @@api_key          = "?key=#{ENV['MEETUP_API_KEY']}"
  @@chicago          = "&city=Chicago&country=us&state=il"
  @@topic            = "&topic="

  def self.fetch_chi_events(api_key: @@api_key, city: @@chicago)
    puts "fetching all events"

    # returns an array of game hashes with keys:
    # id, title, long_title, images
    HTTParty.get(@@events_root + api_key + city)
  end

  def self.fetch_chi_events_search(search = "")
    puts "fetching search events"
    p search[:search]
    # returns an array of game hashes with keys:
    # id, title, long_title, images
    HTTParty.get(@@events_root + @@api_key + @@chicago + @@topic + search[:search])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
require "pp"
require 'JSON'
class EventsController < ApplicationController
  def index
    if event_params["search"] && event_params["search"] != ""
      @events = Meetup.fetch_chi_events_search(search: event_params["search"])
    else
      @events = Meetup.fetch_chi_events
    end
    @events = @events["results"]
    @events = set_start_time(@events)

    # converts events to an openstruct, needed for simplecal gem
    @events = JSON.parse(@events.to_json, object_class: OpenStruct)
  end

  private

  def event_params
    params.permit(:search)
  end

  def set_start_time(events)
    events.each do |event|
      event[:start_time] = Time.at(event["time"] / 1000)
    end
    events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_calendar.html.erb
<div class="container">
  <%= month_calendar events: events do |date, events| %>
    <div class="dailyinfo text-center">
      <span class="p small" style=""><%= date.to_s[-2..-1] %></span>
    </div>

    <% events.each do |event| %>
      <div class="row">
        <div class="col-md-12" style="margin-bottom:10px; max-width:200px">
          <%= link_to event["name"], event["event_url"] %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="row pad-bot-lg">
  <div class="col-md-6 col-lg-6 col-xs-12 hidden-xs col-sm-6">
    <div class="input-group" style="padding-top:2px">
      <div class="input-append">
        <%= form_tag(events_path, :method => "get", class: "navbar-form", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], class: "form-control btn-border", placeholder: "Search Items" %>

          <button class="btn btn-warning btn-border" type="submit">&nbsp;search&nbsp;</button>
        <% end %>
      </div>
    </div>
  </div>

<div class="row" style="padding-bottom:15px">
    <div id="events_calendar">
      <%= render partial: "/events/calendar", locals: {events: @events} %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChiEventCalendar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>